version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/circleci-01

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install
       
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
               
      - run: sudo npm install -g @angular/cli@latest
            
      - run: ng build
        
      # run tests!
      - run: ng e2e
  
  deploy:
        working_directory: ~/circleci-01
        docker:
            - image: circleci/node:9-browsers
        steps:
            - checkout
            - run:
              name: Deploy Master to Heroku
              command: |
                git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
        
workflows:
  version: 2
    # The build and deploy workflow
  build_and_deploy:
    jobs:
      - build
      - deploy
